name: ci

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    strategy:
      matrix:
        tool: [ "epix", "gics", "gpas" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/knoppiks/mosaic-${{ matrix['tool'] }}
        tags: |
          type=sha,format=long,prefix=
          type=match,pattern=(\d+.\d+.\d+-k\d+)?,group=0
          type=match,pattern=(\d+.\d+.\d+)(-k\d+)?,group=1
          type=match,pattern=(\d+.\d+).\d+(-k\d+)?,group=1
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Download ${{ matrix['tool'] }}
      run: wget "$(cat .github/${{ matrix['tool'] }}.url)" -qO tool.zip

    - name: Unzip ${{ matrix['tool'] }}
      run: unzip tool.zip && mv ${{ matrix['tool'] }}-* tool

    - name: Uppercase Tool Name
      run: echo "TOOL_NAME_UPPER=${TOOL_NAME^^}" >>${GITHUB_ENV}
      env:
        TOOL_NAME: ${{ matrix['tool'] }}

    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          TOOL_NAME=${{ matrix['tool'] }}
          TOOL_NAME_UPPER=${{ env.TOOL_NAME_UPPER }}

    - name: Test Startup
      run: |
        envsubst '$TOOL_NAME' <compose.tmpl.yml >compose.yml
        docker compose pull -q ${{ matrix['tool'] }}-db
        docker compose up --wait --pull never
      env:
        TOOL_NAME: ${{ matrix['tool'] }}
        IMAGE_TAG: ${{ github.sha }}
